spring:
  application:
    name: vaccine_reservation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vaccine_reservation
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）

server:
  port: 8080

wx:
  miniapp:
    appid: "小程序ID"
    secret: "小程序密钥"
